name: esmfold_mac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch>=2.0
  - torchvision
  - pandas
  - biopython
  - tqdm
  - numpy
  - pip:
      - fair-esm
      - omegaconf
      - dm-tree
      - git+https://github.com/aqlaboratory/openfold.git
